/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as KarirRouteImport } from './routes/karir'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as BlogPostIdRouteImport } from './routes/blog_.$postId'
import { Route as KarirJobIdRouteImport } from './routes/karir_.$jobId'
import { Route as ApiMobileImageProxyRouteImport } from './routes/api/mobile/image-proxy'
import { Route as ApiMobileItemGroupsRouteImport } from './routes/api/mobile/item-groups'
import { Route as ApiMobileLoyaltyRouteImport } from './routes/api/mobile/loyalty'
import { Route as ApiMobileOrdersRouteImport } from './routes/api/mobile/orders'
import { Route as ApiMobileOutletsRouteImport } from './routes/api/mobile/outlets'
import { Route as ApiMobileProductsRouteImport } from './routes/api/mobile/products'
import { Route as ApiMobilePromoBannersRouteImport } from './routes/api/mobile/promo-banners'
import { Route as ApiMobilePromoProductsRouteImport } from './routes/api/mobile/promo-products'
import { Route as ApiMobileAuthLoginRouteImport } from './routes/api/mobile/auth.login'
import { Route as ApiMobileAuthLogoutRouteImport } from './routes/api/mobile/auth.logout'
import { Route as ApiMobileAuthMeRouteImport } from './routes/api/mobile/auth.me'
import { Route as ApiMobileProductsIdRouteImport } from './routes/api/mobile/products_.$id'
import { Route as ApiMobileAuthGoogleCallbackRouteImport } from './routes/api/mobile/auth.google.callback'
import { Route as ApiMobileAuthGoogleStartRouteImport } from './routes/api/mobile/auth.google.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KarirRoute = KarirRouteImport.update({
  id: '/karir',
  path: '/karir',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog_/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const KarirJobIdRoute = KarirJobIdRouteImport.update({
  id: '/karir_/$jobId',
  path: '/karir/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileImageProxyRoute = ApiMobileImageProxyRouteImport.update({
  id: '/api/mobile/image-proxy',
  path: '/api/mobile/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileItemGroupsRoute = ApiMobileItemGroupsRouteImport.update({
  id: '/api/mobile/item-groups',
  path: '/api/mobile/item-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileLoyaltyRoute = ApiMobileLoyaltyRouteImport.update({
  id: '/api/mobile/loyalty',
  path: '/api/mobile/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileOrdersRoute = ApiMobileOrdersRouteImport.update({
  id: '/api/mobile/orders',
  path: '/api/mobile/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileOutletsRoute = ApiMobileOutletsRouteImport.update({
  id: '/api/mobile/outlets',
  path: '/api/mobile/outlets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileProductsRoute = ApiMobileProductsRouteImport.update({
  id: '/api/mobile/products',
  path: '/api/mobile/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePromoBannersRoute = ApiMobilePromoBannersRouteImport.update({
  id: '/api/mobile/promo-banners',
  path: '/api/mobile/promo-banners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePromoProductsRoute = ApiMobilePromoProductsRouteImport.update({
  id: '/api/mobile/promo-products',
  path: '/api/mobile/promo-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthLoginRoute = ApiMobileAuthLoginRouteImport.update({
  id: '/api/mobile/auth/login',
  path: '/api/mobile/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthLogoutRoute = ApiMobileAuthLogoutRouteImport.update({
  id: '/api/mobile/auth/logout',
  path: '/api/mobile/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthMeRoute = ApiMobileAuthMeRouteImport.update({
  id: '/api/mobile/auth/me',
  path: '/api/mobile/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileProductsIdRoute = ApiMobileProductsIdRouteImport.update({
  id: '/api/mobile/products_/$id',
  path: '/api/mobile/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthGoogleCallbackRoute =
  ApiMobileAuthGoogleCallbackRouteImport.update({
    id: '/api/mobile/auth/google/callback',
    path: '/api/mobile/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileAuthGoogleStartRoute =
  ApiMobileAuthGoogleStartRouteImport.update({
    id: '/api/mobile/auth/google/start',
    path: '/api/mobile/auth/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/blog': typeof BlogRoute
  '/karir': typeof KarirRoute
  '/katalog': typeof KatalogRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/tentang': typeof TentangRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/karir/$jobId': typeof KarirJobIdRoute
  '/api/mobile/image-proxy': typeof ApiMobileImageProxyRoute
  '/api/mobile/item-groups': typeof ApiMobileItemGroupsRoute
  '/api/mobile/loyalty': typeof ApiMobileLoyaltyRoute
  '/api/mobile/orders': typeof ApiMobileOrdersRoute
  '/api/mobile/outlets': typeof ApiMobileOutletsRoute
  '/api/mobile/products': typeof ApiMobileProductsRoute
  '/api/mobile/promo-banners': typeof ApiMobilePromoBannersRoute
  '/api/mobile/promo-products': typeof ApiMobilePromoProductsRoute
  '/api/mobile/auth/login': typeof ApiMobileAuthLoginRoute
  '/api/mobile/auth/logout': typeof ApiMobileAuthLogoutRoute
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/products/$id': typeof ApiMobileProductsIdRoute
  '/api/mobile/auth/google/callback': typeof ApiMobileAuthGoogleCallbackRoute
  '/api/mobile/auth/google/start': typeof ApiMobileAuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/blog': typeof BlogRoute
  '/karir': typeof KarirRoute
  '/katalog': typeof KatalogRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/tentang': typeof TentangRoute
  '/blog/$postId': typeof BlogPostIdRoute
  '/karir/$jobId': typeof KarirJobIdRoute
  '/api/mobile/image-proxy': typeof ApiMobileImageProxyRoute
  '/api/mobile/item-groups': typeof ApiMobileItemGroupsRoute
  '/api/mobile/loyalty': typeof ApiMobileLoyaltyRoute
  '/api/mobile/orders': typeof ApiMobileOrdersRoute
  '/api/mobile/outlets': typeof ApiMobileOutletsRoute
  '/api/mobile/products': typeof ApiMobileProductsRoute
  '/api/mobile/promo-banners': typeof ApiMobilePromoBannersRoute
  '/api/mobile/promo-products': typeof ApiMobilePromoProductsRoute
  '/api/mobile/auth/login': typeof ApiMobileAuthLoginRoute
  '/api/mobile/auth/logout': typeof ApiMobileAuthLogoutRoute
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/products/$id': typeof ApiMobileProductsIdRoute
  '/api/mobile/auth/google/callback': typeof ApiMobileAuthGoogleCallbackRoute
  '/api/mobile/auth/google/start': typeof ApiMobileAuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/blog': typeof BlogRoute
  '/karir': typeof KarirRoute
  '/katalog': typeof KatalogRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/tentang': typeof TentangRoute
  '/blog_/$postId': typeof BlogPostIdRoute
  '/karir_/$jobId': typeof KarirJobIdRoute
  '/api/mobile/image-proxy': typeof ApiMobileImageProxyRoute
  '/api/mobile/item-groups': typeof ApiMobileItemGroupsRoute
  '/api/mobile/loyalty': typeof ApiMobileLoyaltyRoute
  '/api/mobile/orders': typeof ApiMobileOrdersRoute
  '/api/mobile/outlets': typeof ApiMobileOutletsRoute
  '/api/mobile/products': typeof ApiMobileProductsRoute
  '/api/mobile/promo-banners': typeof ApiMobilePromoBannersRoute
  '/api/mobile/promo-products': typeof ApiMobilePromoProductsRoute
  '/api/mobile/auth/login': typeof ApiMobileAuthLoginRoute
  '/api/mobile/auth/logout': typeof ApiMobileAuthLogoutRoute
  '/api/mobile/auth/me': typeof ApiMobileAuthMeRoute
  '/api/mobile/products_/$id': typeof ApiMobileProductsIdRoute
  '/api/mobile/auth/google/callback': typeof ApiMobileAuthGoogleCallbackRoute
  '/api/mobile/auth/google/start': typeof ApiMobileAuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akun'
    | '/blog'
    | '/karir'
    | '/katalog'
    | '/kontak'
    | '/login'
    | '/member'
    | '/profil'
    | '/promo'
    | '/tentang'
    | '/blog/$postId'
    | '/karir/$jobId'
    | '/api/mobile/image-proxy'
    | '/api/mobile/item-groups'
    | '/api/mobile/loyalty'
    | '/api/mobile/orders'
    | '/api/mobile/outlets'
    | '/api/mobile/products'
    | '/api/mobile/promo-banners'
    | '/api/mobile/promo-products'
    | '/api/mobile/auth/login'
    | '/api/mobile/auth/logout'
    | '/api/mobile/auth/me'
    | '/api/mobile/products/$id'
    | '/api/mobile/auth/google/callback'
    | '/api/mobile/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akun'
    | '/blog'
    | '/karir'
    | '/katalog'
    | '/kontak'
    | '/login'
    | '/member'
    | '/profil'
    | '/promo'
    | '/tentang'
    | '/blog/$postId'
    | '/karir/$jobId'
    | '/api/mobile/image-proxy'
    | '/api/mobile/item-groups'
    | '/api/mobile/loyalty'
    | '/api/mobile/orders'
    | '/api/mobile/outlets'
    | '/api/mobile/products'
    | '/api/mobile/promo-banners'
    | '/api/mobile/promo-products'
    | '/api/mobile/auth/login'
    | '/api/mobile/auth/logout'
    | '/api/mobile/auth/me'
    | '/api/mobile/products/$id'
    | '/api/mobile/auth/google/callback'
    | '/api/mobile/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/akun'
    | '/blog'
    | '/karir'
    | '/katalog'
    | '/kontak'
    | '/login'
    | '/member'
    | '/profil'
    | '/promo'
    | '/tentang'
    | '/blog_/$postId'
    | '/karir_/$jobId'
    | '/api/mobile/image-proxy'
    | '/api/mobile/item-groups'
    | '/api/mobile/loyalty'
    | '/api/mobile/orders'
    | '/api/mobile/outlets'
    | '/api/mobile/products'
    | '/api/mobile/promo-banners'
    | '/api/mobile/promo-products'
    | '/api/mobile/auth/login'
    | '/api/mobile/auth/logout'
    | '/api/mobile/auth/me'
    | '/api/mobile/products_/$id'
    | '/api/mobile/auth/google/callback'
    | '/api/mobile/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkunRoute: typeof AkunRoute
  BlogRoute: typeof BlogRoute
  KarirRoute: typeof KarirRoute
  KatalogRoute: typeof KatalogRoute
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRoute
  ProfilRoute: typeof ProfilRoute
  PromoRoute: typeof PromoRoute
  TentangRoute: typeof TentangRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
  KarirJobIdRoute: typeof KarirJobIdRoute
  ApiMobileImageProxyRoute: typeof ApiMobileImageProxyRoute
  ApiMobileItemGroupsRoute: typeof ApiMobileItemGroupsRoute
  ApiMobileLoyaltyRoute: typeof ApiMobileLoyaltyRoute
  ApiMobileOrdersRoute: typeof ApiMobileOrdersRoute
  ApiMobileOutletsRoute: typeof ApiMobileOutletsRoute
  ApiMobileProductsRoute: typeof ApiMobileProductsRoute
  ApiMobilePromoBannersRoute: typeof ApiMobilePromoBannersRoute
  ApiMobilePromoProductsRoute: typeof ApiMobilePromoProductsRoute
  ApiMobileAuthLoginRoute: typeof ApiMobileAuthLoginRoute
  ApiMobileAuthLogoutRoute: typeof ApiMobileAuthLogoutRoute
  ApiMobileAuthMeRoute: typeof ApiMobileAuthMeRoute
  ApiMobileProductsIdRoute: typeof ApiMobileProductsIdRoute
  ApiMobileAuthGoogleCallbackRoute: typeof ApiMobileAuthGoogleCallbackRoute
  ApiMobileAuthGoogleStartRoute: typeof ApiMobileAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karir': {
      id: '/karir'
      path: '/karir'
      fullPath: '/karir'
      preLoaderRoute: typeof KarirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$postId': {
      id: '/blog_/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karir_/$jobId': {
      id: '/karir_/$jobId'
      path: '/karir/$jobId'
      fullPath: '/karir/$jobId'
      preLoaderRoute: typeof KarirJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/image-proxy': {
      id: '/api/mobile/image-proxy'
      path: '/api/mobile/image-proxy'
      fullPath: '/api/mobile/image-proxy'
      preLoaderRoute: typeof ApiMobileImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/item-groups': {
      id: '/api/mobile/item-groups'
      path: '/api/mobile/item-groups'
      fullPath: '/api/mobile/item-groups'
      preLoaderRoute: typeof ApiMobileItemGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/loyalty': {
      id: '/api/mobile/loyalty'
      path: '/api/mobile/loyalty'
      fullPath: '/api/mobile/loyalty'
      preLoaderRoute: typeof ApiMobileLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/orders': {
      id: '/api/mobile/orders'
      path: '/api/mobile/orders'
      fullPath: '/api/mobile/orders'
      preLoaderRoute: typeof ApiMobileOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/outlets': {
      id: '/api/mobile/outlets'
      path: '/api/mobile/outlets'
      fullPath: '/api/mobile/outlets'
      preLoaderRoute: typeof ApiMobileOutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/products': {
      id: '/api/mobile/products'
      path: '/api/mobile/products'
      fullPath: '/api/mobile/products'
      preLoaderRoute: typeof ApiMobileProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/promo-banners': {
      id: '/api/mobile/promo-banners'
      path: '/api/mobile/promo-banners'
      fullPath: '/api/mobile/promo-banners'
      preLoaderRoute: typeof ApiMobilePromoBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/promo-products': {
      id: '/api/mobile/promo-products'
      path: '/api/mobile/promo-products'
      fullPath: '/api/mobile/promo-products'
      preLoaderRoute: typeof ApiMobilePromoProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/login': {
      id: '/api/mobile/auth/login'
      path: '/api/mobile/auth/login'
      fullPath: '/api/mobile/auth/login'
      preLoaderRoute: typeof ApiMobileAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/logout': {
      id: '/api/mobile/auth/logout'
      path: '/api/mobile/auth/logout'
      fullPath: '/api/mobile/auth/logout'
      preLoaderRoute: typeof ApiMobileAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/me': {
      id: '/api/mobile/auth/me'
      path: '/api/mobile/auth/me'
      fullPath: '/api/mobile/auth/me'
      preLoaderRoute: typeof ApiMobileAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/products_/$id': {
      id: '/api/mobile/products_/$id'
      path: '/api/mobile/products/$id'
      fullPath: '/api/mobile/products/$id'
      preLoaderRoute: typeof ApiMobileProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/google/callback': {
      id: '/api/mobile/auth/google/callback'
      path: '/api/mobile/auth/google/callback'
      fullPath: '/api/mobile/auth/google/callback'
      preLoaderRoute: typeof ApiMobileAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth/google/start': {
      id: '/api/mobile/auth/google/start'
      path: '/api/mobile/auth/google/start'
      fullPath: '/api/mobile/auth/google/start'
      preLoaderRoute: typeof ApiMobileAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkunRoute: AkunRoute,
  BlogRoute: BlogRoute,
  KarirRoute: KarirRoute,
  KatalogRoute: KatalogRoute,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRoute,
  ProfilRoute: ProfilRoute,
  PromoRoute: PromoRoute,
  TentangRoute: TentangRoute,
  BlogPostIdRoute: BlogPostIdRoute,
  KarirJobIdRoute: KarirJobIdRoute,
  ApiMobileImageProxyRoute: ApiMobileImageProxyRoute,
  ApiMobileItemGroupsRoute: ApiMobileItemGroupsRoute,
  ApiMobileLoyaltyRoute: ApiMobileLoyaltyRoute,
  ApiMobileOrdersRoute: ApiMobileOrdersRoute,
  ApiMobileOutletsRoute: ApiMobileOutletsRoute,
  ApiMobileProductsRoute: ApiMobileProductsRoute,
  ApiMobilePromoBannersRoute: ApiMobilePromoBannersRoute,
  ApiMobilePromoProductsRoute: ApiMobilePromoProductsRoute,
  ApiMobileAuthLoginRoute: ApiMobileAuthLoginRoute,
  ApiMobileAuthLogoutRoute: ApiMobileAuthLogoutRoute,
  ApiMobileAuthMeRoute: ApiMobileAuthMeRoute,
  ApiMobileProductsIdRoute: ApiMobileProductsIdRoute,
  ApiMobileAuthGoogleCallbackRoute: ApiMobileAuthGoogleCallbackRoute,
  ApiMobileAuthGoogleStartRoute: ApiMobileAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
